### ISSUE TITLE
Timetable returns server error 500

### ISSUE THREAD

**Issue by balping** [uclapi/uclapi#782] opened 2018-11-09 21:02 UTC
The personal time table endpoint returns server error 500 for me. As there hasn't been any change in the codebase, I suspect that one recently added timetable entry causes the error:

![tt](https://user-images.githubusercontent.com/5840038/48287925-69ef0480-e462-11e8-8f0a-b06113f909a1.png)

The above entry is marked as "meeting" which is unusual. That's my only guess why the timetable has stopped working for me.

Could you please investigate this?

**Comment by ChristopherHammond13** [comment] 2018-11-09 21:16
Hey! I've seen some errors trickle through so you're not doing anything wrong.

I'll investigate and let you know. Thanks for raising!

**Comment by balping** [comment] 2018-11-12 11:08
Please... My app has stopped working because of this.

**Comment by ChristopherHammond13** [comment] 2018-11-12 16:35
This seems to be okay now, and caused by a temporary caching issue so I'm going to close the issue. If this appears again I'll check the code over to try and understand why.

**Closed by ChristopherHammond13** 2018-11-12 16:35 UTC
Labels: bug
